### ISSUE TITLE
Add unit tests, javadoc

### ISSUE THREAD

**Issue by MakoStrwlkr** [CSC207-UofT/course-project-uwutever#25]
Include javadoc for every class in project;
Add unit tests for every feature of project;
Add demo for phase 2.

**Comment by RealFakeAccount** [comment]
I finished javadoc for UI yesterday. Please check it.

**Comment by FrayeY** [comment]
unittests for both NFA operation classes are complete, along with NFABuilder apart from the addTransition methods.
