### ISSUE TITLE
Error while intergrating

### ISSUE THREAD

**Issue by RealFakeAccount** [CSC207-UofT/course-project-uwutever#27]
While intergrating, this error pop up in file ./parser/Parser:

![image](https://user-images.githubusercontent.com/63186767/144769697-22b5688c-e1dc-4fe3-850d-65a9c33a273a.png)

I think it is coming from backend. Would you mind looking into it?

**Comment by bbrianh** [comment]
fixed try now

**Comment by bbrianh** [comment]
Fixed
